# Generated by Django 3.2.8 on 2021-10-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gisproject',
            old_name='Title_2',
            new_name='Section_Title_2',
        ),
        migrations.RenameField(
            model_name='gisproject',
            old_name='Title_3',
            new_name='Section_Title_3',
        ),
        migrations.RenameField(
            model_name='jsproject',
            old_name='Title_2',
            new_name='Section_Title_2',
        ),
        migrations.RenameField(
            model_name='jsproject',
            old_name='Title_3',
            new_name='Section_Title_3',
        ),
        migrations.RenameField(
            model_name='pythonproject',
            old_name='Title_2',
            new_name='Section_Title_2',
        ),
        migrations.RenameField(
            model_name='pythonproject',
            old_name='Title_3',
            new_name='Section_Title_3',
        ),
        migrations.AddField(
            model_name='gisproject',
            name='Section_Title_1',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='jsproject',
            name='Section_Title_1',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='pythonproject',
            name='Section_Title_1',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
