# Generated by Django 3.2.8 on 2021-10-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211016_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisproject',
            name='Section_Title_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gisproject',
            name='Section_Title_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gisproject',
            name='Section_Title_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gisproject',
            name='Title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jsproject',
            name='Section_Title_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jsproject',
            name='Section_Title_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jsproject',
            name='Section_Title_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jsproject',
            name='Title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pythonproject',
            name='Section_Title_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pythonproject',
            name='Section_Title_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pythonproject',
            name='Section_Title_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pythonproject',
            name='Title',
            field=models.CharField(max_length=30),
        ),
    ]
